WITH TEMP AS(
    SELECT NAME,OCCUPATION, ROW_NUMBER() OVER(
        PARTITION BY OCCUPATION
        ORDER BY NAME
    )RN
    
    FROM OCCUPATIONS
)
SELECT 
   MAX(CASE WHEN OCCUPATION='DOCTOR' THEN NAME  END),
   MAX(CASE WHEN OCCUPATION='PROFESSOR' THEN NAME END),
   MAX(CASE WHEN OCCUPATION='SINGER' THEN NAME END),
   MAX(CASE WHEN OCCUPATION='ACTOR' THEN NAME END)
FROM TEMP
GROUP BY RN
ORDER BY RN;
