SELECT C.COMPANY_CODE, C.FOUNDER , COUNT(DISTINCT L.LEAD_MANAGER_CODE),
COUNT(DISTINCT S.SENIOR_MANAGER_CODE),COUNT(DISTINCT M.MANAGER_CODE),
COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM Company C
JOIN Lead_Manager L ON C.COMPANY_CODE=L.COMPANY_CODE
JOIN Senior_Manager S ON L.COMPANY_CODE=S.COMPANY_CODE
JOIN Manager M ON S.COMPANY_CODE=M.COMPANY_CODE
JOIN Employee E ON M.COMPANY_CODE=E.COMPANY_CODE
GROUP BY C.COMPANY_CODE,C.FOUNDER
ORDER BY C.COMPANY_CODE
